export const expressionLabels: Record<string, string> = {
  admiration: "Hayranlık",
  adoration: "Tapınma",
  aestheticAppreciation: "Estetik Takdir",
  amusement: "Eğlence",
  anger: "Öfke",
  annoyance: "Rahatsızlık",
  anxiety: "Kaygı",
  awe: "Korku",
  awkwardness: "Gariplik",
  boredom: "Can Sıkıntısı",
  calmness: "Sakinlik",
  concentration: "Konsantrasyon",
  contemplation: "Düşünce",
  confusion: "Kafa Karışıklığı",
  contempt: "Aşağılama",
  contentment: "Memnuniyet",
  craving: "Arzu",
  determination: "Kararlılık",
  disappointment: "Hayal Kırıklığı",
  disapproval: "Onaylamama",
  disgust: "Tiksinti",
  distress: "Sıkıntı",
  doubt: "Şüphe",
  ecstasy: "Coşku",
  embarrassment: "Utanç",
  empathicPain: "Empatik Acı",
  enthusiasm: "Coşku",
  entrancement: "Büyülenme",
  envy: "Kıskançlık",
  excitement: "Heyecan",
  fear: "Korku",
  gratitude: "Minnettarlık",
  guilt: "Suçluluk",
  horror: "Dehşet",
  interest: "İlgi",
  joy: "Neşe",
  love: "Aşk",
  neutral: "Nötr",
  nostalgia: "Nostalji",
  pain: "Acı",
  pride: "Gurur",
  realization: "Farkındalık",
  relief: "Rahatlama",
  romance: "Romantizm",
  sadness: "Üzüntü",
  sarcasm: "Alay",
  satisfaction: "Tatmin",
  sexualDesire: "Cinsel Arzu",
  shame: "Utanç",
  surprise: "Sürpriz",
  surpriseNegative: "Sürpriz (Negatif)",
  surprisePositive: "Sürpriz (Pozitif)",
  sympathy: "Sempati",
  tiredness: "Yorgunluk",
  triumph: "Zafer",
};
